version: "3.8"

services:
  mdi:
    image: africahazardswatch/mdi:latest
    container_name: mdi
    build: .
    restart: ${RESTART_POLICY}
    environment:
      - CDS_API_KEY=${CDS_API_KEY}
      - SHP_CLIP_PATH=/home/node/app/src/shp/africa.shp
      - MINUTES_BEFORE_RETRY=${MINUTES_BEFORE_RETRY}
      - MINUTES_BEFORE_TIMEOUT=${MINUTES_BEFORE_TIMEOUT}
      - GSKY_ERA5_INGEST_WEBHOOK_ENDPOINT=${GSKY_ERA5_INGEST_WEBHOOK_ENDPOINT}
      - GSKY_ERA5_INGEST_SCRIPT_FILENAME=${GSKY_ERA5_INGEST_SCRIPT_FILENAME}
      - GSKY_WEHBOOK_SECRET=${GSKY_WEHBOOK_SECRET}
    volumes:
      - ${DATA_VOLUME}:/home/node/app/public/mdi
      - ${DATA_STATE_VOLUME}:/home/node/app/src/state
      - ${DATA_CACHE_VOLUME}:/home/node/app/src/cache

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true